### ISSUE TITLE
Native Bitwarden App Support

### ISSUE THREAD

**Issue by ayrudev** [Y0ngg4n/vaultwarden-net-frontpage#7]
hey there, just asking, is there an ETA for merging Vaultwarden's [#4671](https://github.com/dani-garcia/vaultwarden/pull/4671) pr that fixes the errors w/ the new app?

**Comment by Y0ngg4n** [comment]
@Polarzincomfrio What do you mean? On vault.vaultwarden.net is already the latest version running?

**Comment by ayrudev** [comment]
i think they didn't release the new update, sad, have you tested the new native bitwarden apps on mobile?

**Comment by Y0ngg4n** [comment]
No but i will update vaultwarden when the new version comes out.
